/**
 * Prepares the .open-next build output for Cloudflare Pages deployment.
 *
 * Creates a thin _worker.js entry point and a _routes.json that tells Pages
 * to serve static assets directly from CDN and route dynamic requests through
 * the worker generated by OpenNext.
 */
import { writeFileSync, existsSync } from 'node:fs';

const required = [
  '.open-next/cloudflare/images.js',
  '.open-next/cloudflare/init.js',
  '.open-next/cloudflare/skew-protection.js',
  '.open-next/middleware/handler.mjs',
  '.open-next/server-functions/default/handler.mjs',
  '.open-next/.build/durable-objects/queue.js',
  '.open-next/.build/durable-objects/sharded-tag-cache.js',
  '.open-next/.build/durable-objects/bucket-cache-purge.js',
];

for (const file of required) {
  if (!existsSync(file)) {
    console.error(`Missing expected build artifact: ${file}`);
    console.error('The prepare-pages script may need updating if @opennextjs/cloudflare changed its output structure.');
    process.exit(1);
  }
}

const dest = '.open-next/assets';

const workerEntry = `// Auto-generated Pages entry point
import { handleCdnCgiImageRequest, handleImageRequest } from "../cloudflare/images.js";
import { runWithCloudflareRequestContext } from "../cloudflare/init.js";
import { maybeGetSkewProtectionResponse } from "../cloudflare/skew-protection.js";
import { handler as middlewareHandler } from "../middleware/handler.mjs";
export { DOQueueHandler } from "../.build/durable-objects/queue.js";
export { DOShardedTagCache } from "../.build/durable-objects/sharded-tag-cache.js";
export { BucketCachePurge } from "../.build/durable-objects/bucket-cache-purge.js";
export default {
  async fetch(request, env, ctx) {
    return runWithCloudflareRequestContext(request, env, ctx, async () => {
      const response = maybeGetSkewProtectionResponse(request);
      if (response) return response;
      const url = new URL(request.url);
      if (url.pathname.startsWith("/cdn-cgi/image/")) {
        return handleCdnCgiImageRequest(url, env);
      }
      if (url.pathname === \`${globalThis.__NEXT_BASE_PATH__}/_next/image${globalThis.__TRAILING_SLASH__ ? "/" : ""}\`) {
        return await handleImageRequest(url, request.headers, env);
      }
      const reqOrResp = await middlewareHandler(request, env, ctx);
      if (reqOrResp instanceof Response) return reqOrResp;
      const { handler } = await import("../server-functions/default/handler.mjs");
      return handler(reqOrResp, env, ctx, request.signal);
    });
  },
};
`;

const routes = {
  version: 1,
  include: ['/*'],
  exclude: [
    '/_next/static/*',
    '/*.ico',
    '/*.png',
    '/*.svg',
    '/*.jpg',
    '/*.jpeg',
    '/*.webp',
    '/*.gif',
    '/*.txt',
    '/*.xml',
    '/BUILD_ID',
  ],
};

writeFileSync(`${dest}/_worker.js`, workerEntry);
writeFileSync(`${dest}/_routes.json`, JSON.stringify(routes, null, 2));
console.log('Pages output prepared: _worker.js + _routes.json');
