import type { Trace, Span } from '@foxhound/types';

interface DiffMetrics {
  cost: { valueA: number; valueB: number; delta: number; percentage: number };
  duration: { valueA: number; valueB: number; delta: number; percentage: number };
  spans: { valueA: number; valueB: number; delta: number };
  errors: { valueA: number; valueB: number; delta: number };
}

interface SpanDiff {
  added: Span[];
  removed: Span[];
  modified: Span[];
  unchanged: Span[];
}

function formatCurrency(v: number): string {
  return `$${v.toFixed(4)}`;
}

function formatDelta(v: number, format: 'currency' | 'duration' | 'number'): string {
  const sign = v > 0 ? '+' : '';
  switch (format) {
    case 'currency': return `${sign}$${v.toFixed(4)}`;
    case 'duration': return `${sign}${v.toFixed(2)}s`;
    case 'number': return `${sign}${v}`;
  }
}

export function exportDiffAsMarkdown(
  traceA: Trace,
  traceB: Trace,
  metrics: DiffMetrics,
  spanDiff: SpanDiff,
  verdict: { headline: string; summary: string },
): string {
  const storyA = typeof traceA.metadata?.story_label === 'string' ? traceA.metadata.story_label : traceA.id;
  const storyB = typeof traceB.metadata?.story_label === 'string' ? traceB.metadata.story_label : traceB.id;

  const lines: string[] = [];
  lines.push(`# Run Diff Report`);
  lines.push('');
  lines.push(`**${verdict.headline}**`);
  lines.push('');
  lines.push(verdict.summary);
  lines.push('');

  lines.push('## Traces');
  lines.push('');
  lines.push(`| | Baseline (A) | Comparison (B) |`);
  lines.push(`|---|---|---|`);
  lines.push(`| **Label** | ${storyA} | ${storyB} |`);
  lines.push(`| **Agent** | ${traceA.agentId} | ${traceB.agentId} |`);
  lines.push(`| **ID** | \`${traceA.id}\` | \`${traceB.id}\` |`);
  lines.push('');

  lines.push('## Metrics');
  lines.push('');
  lines.push('| Metric | A | B | Delta |');
  lines.push('|---|---|---|---|');
  lines.push(`| Cost | ${formatCurrency(metrics.cost.valueA)} | ${formatCurrency(metrics.cost.valueB)} | ${formatDelta(metrics.cost.delta, 'currency')} (${metrics.cost.percentage > 0 ? '+' : ''}${metrics.cost.percentage.toFixed(0)}%) |`);
  lines.push(`| Duration | ${metrics.duration.valueA.toFixed(2)}s | ${metrics.duration.valueB.toFixed(2)}s | ${formatDelta(metrics.duration.delta, 'duration')} (${metrics.duration.percentage > 0 ? '+' : ''}${metrics.duration.percentage.toFixed(0)}%) |`);
  lines.push(`| Spans | ${metrics.spans.valueA} | ${metrics.spans.valueB} | ${formatDelta(metrics.spans.delta, 'number')} |`);
  lines.push(`| Errors | ${metrics.errors.valueA} | ${metrics.errors.valueB} | ${formatDelta(metrics.errors.delta, 'number')} |`);
  lines.push('');

  if (spanDiff.added.length > 0 || spanDiff.removed.length > 0 || spanDiff.modified.length > 0) {
    lines.push('## Span Changes');
    lines.push('');
    if (spanDiff.added.length > 0) {
      lines.push(`**Added in B (${spanDiff.added.length}):** ${spanDiff.added.map((s) => s.name).join(', ')}`);
      lines.push('');
    }
    if (spanDiff.removed.length > 0) {
      lines.push(`**Removed from A (${spanDiff.removed.length}):** ${spanDiff.removed.map((s) => s.name).join(', ')}`);
      lines.push('');
    }
    if (spanDiff.modified.length > 0) {
      lines.push(`**Modified (${spanDiff.modified.length}):** ${spanDiff.modified.map((s) => s.name).join(', ')}`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push(`*Generated by Foxhound at ${new Date().toISOString()}*`);

  return lines.join('\n');
}

export function copyToClipboard(text: string) {
  navigator.clipboard.writeText(text);
}
